---
- name: Validate successful deployment of application
  hosts: localhost
  gather_facts: false
  vars:
     resource_group: "openenv-5x9h7"
     appgw_name: "my-app-gateway"
     backend_pool_name: "my-pool-1"
     health_probe_name: "my-probe-aap"
     
  tasks:
      
    - name: stop gateway
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        gateway_state: stopped

    - name: Gather facts about the existing Application Gateway
      azure.azcollection.azure_rm_appgateway_info:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
      register: existing_gateway_facts

    - name: Display existing gateway
      debug:
        var: existing_gateway_facts

    - name: 2. Define the new backend pool to be added
      set_fact:
        new_backend_pool:
          - name: ansible-managed-pool-1   # Name of the new backend pool
            backend_addresses:          # You can use ip_addresses or fqdns
              - 10.9.0.101
              - 10.9.0.102
    
    - name: 3. Combine existing pools with the new pool
      set_fact:
        # This creates a final list containing all old pools and the new one.
        # The 'default([])' filter handles cases where no pools exist yet.
        combined_pools: "{{ existing_gateway_facts.application_gateways[0].backend_address_pools | default([]) + new_backend_pool }}"

    - name: Start Gateway
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        state: present
        gateway_state: started
      register: app_gateway_output
      
    - name: Display new gateway
      debug:
        var: app_gateway_output

    - name: Display new gateway
      debug:
        var: app_gateway_output.state.backend_address_pools
