---
- name: Validate successful deployment of application
  hosts: localhost
  gather_facts: false
  vars:
     resource_group: "openenv-5x9h7"
     appgw_name: "my-app-gateway"
     backend_pool_name: "my-pool-1"
     health_probe_name: "my-probe-aap"
  tasks:
      
    - name: Update Azure Application Gateway with new backend pool, health probe, backend setting, and path rule
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        gateway_state: stopped
