---
- name: Validate successful deployment of application
  hosts: localhost
  gather_facts: false
  vars:
     resource_group: "openenv-5x9h7"
     appgw_name: "my-app-gateway"
     backend_pool_name: "my-pool-1"
     health_probe_name: "my-probe-aap"
     
  tasks:
      
    - name: stop gateway
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        gateway_state: stopped

    - name: Update Azure Application Gateway with new backend pool, health probe, backend setting, and path rule
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        gateway_ip_configurations:
          - subnet:
              id: "{{ gw_subnet_id }}"
        frontend_ip_configurations:
          - subnet:
              id: "{{ fe_subnet_id }}"
        backend_address_pools:
          - name: "my-new-backend-pool"
