---
- name: Validate successful deployment of application
  hosts: localhost
  gather_facts: false
  vars:
     resource_group: "openenv-5x9h7"
     appgw_name: "my-app-gateway-aap"
     backend_pool_name: "my-pool-1"
     health_probe_name: "my-probe-aap"
  tasks:
    - name: Create a subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network_name: aap-mgt-virt-network
        name: aap-mgt-subnet
        address_prefix_cidr: "10.3.0.0/24"
   
    - name: Create instance of Application Gateway
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
        sku:
          name: standard_small
          tier: standard
          capacity: 2
        gateway_ip_configurations:
          - subnet:
              virtual_network_name: aap-mgt-virt-network
              name: aap-mgt-subnet
            name: app_gateway_ip_config
        frontend_ip_configurations:
          - subnet:
              virtual_network_name: aap-mgt-virt-network
              name: aap-mgt-subnet
            name: sample_gateway_frontend_ip_config
        frontend_ports:
          - port: 90
            name: ag_frontend_port
        backend_address_pools:
          - backend_addresses:
              - ip_address: 10.0.0.4
            name: test_backend_address_pool
        backend_http_settings_collection:
          - port: 80
            protocol: http
            cookie_based_affinity: enabled
            connection_draining:
              drain_timeout_in_sec: 60
              enabled: true
            name: sample_appgateway_http_settings
    
