---
- name: edit app gateway
  hosts: localhost
  gather_facts: true
  vars:
     resource_group: "openenv-5x9h7"
     appgw_name: "my-app-gateway-aap"
     backend_pool_name: "my-pool-1"
     health_probe_name: "my-probe-aap"
  tasks:
 
    - name: Edit instance of Application Gateway
      register: app_gateway_output
      state: present
      azure_rm_appgateway:
        resource_group: "{{ resource_group }}"
        name: "{{ appgw_name }}"
               
        backend_address_pools:
          - backend_addresses:
              - ip_address: 10.0.0.4
              - ip_address: 10.0.0.5
            name: test_backend_address_pool

    - name: Display new gateway
      debug:
        var: app_gateway_output
